version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    env_file:
      - .env
    depends_on:
      - redis
      - grobid
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:5173"
    env_file:
      - .env.client
    depends_on:
      - backend
  grobid:
    image: lfoppiano/grobid:0.8.1
    ports:
      - "8070:8070"
    init: true
    ulimits:
      core: 0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]

  redis:
    image: redis:7-alpine